### ISSUE TITLE
Deploy Swagger on Heroku

### ISSUE THREAD

**Issue by AlexGallego7** [realofcheams/ASW-HackerNews#27]

**Comment by immunoz** [comment]
han habido problemas por el rake, pero se ha solucionado

**Comment by ANASinfad** [comment]
¿Como se ha solucionado? tiene que ver con esto?  adding config.secret_key_base = 'YourSecretKeyHere' in my production.rb located at config/environments folder. The 'YourSecretKeyHere' can be generated by run bundle exec rake secret command.

**Comment by AlexGallego7** [comment]
Exacto. El problema venia en la configuracion de la secret key que no hacia match con la que estaba en heroku. Buen apunte!

**Comment by immunoz** [comment]
Genial!, buen trabajo equipo :)
